"""phase5 google sync links

Revision ID: 17c4f83a91d1
Revises: 994803c13672
Create Date: 2026-08-12 13:03:31.896332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c4f83a91d1'
down_revision: Union[str, Sequence[str], None] = '994803c13672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_calendar_event_links',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('google_event_id', sa.String(), nullable=False),
    sa.Column('google_calendar_id', sa.String(), nullable=False),
    sa.Column('google_updated_at', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('google_task_links',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('google_task_id', sa.String(), nullable=False),
    sa.Column('google_list_id', sa.String(), nullable=False),
    sa.Column('google_updated_at', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.add_column('settings', sa.Column('google_sync_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'google_sync_enabled')
    op.drop_table('google_task_links')
    op.drop_table('google_calendar_event_links')
    # ### end Alembic commands ###
