"""phase6 scheduled jobs

Revision ID: b144e5004344
Revises: 0b2347f89ca1
Create Date: 2026-08-12 20:33:07.164519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b144e5004344'
down_revision: Union[str, Sequence[str], None] = '0b2347f89ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_logs',
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('morning_brief_sent', sa.Boolean(), nullable=False),
    sa.Column('evening_checkin_sent', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_date')
    )
    op.add_column(
        'settings',
        sa.Column(
            'morning_brief_time', sa.String(length=5), nullable=False,
            server_default='07:30',
        ),
    )
    op.add_column(
        'settings',
        sa.Column(
            'evening_checkin_time', sa.String(length=5), nullable=False,
            server_default='21:00',
        ),
    )
    op.add_column(
        'settings',
        sa.Column(
            'weekly_review_time', sa.String(length=5), nullable=False,
            server_default='16:00',
        ),
    )
    op.add_column(
        'settings',
        sa.Column(
            'weekly_planning_time', sa.String(length=5), nullable=False,
            server_default='17:00',
        ),
    )
    op.add_column('week_plans', sa.Column('planning_prompt_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('week_plans', 'planning_prompt_sent_at')
    op.drop_column('settings', 'weekly_planning_time')
    op.drop_column('settings', 'weekly_review_time')
    op.drop_column('settings', 'evening_checkin_time')
    op.drop_column('settings', 'morning_brief_time')
    op.drop_table('daily_logs')
    # ### end Alembic commands ###
